config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources 'people'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  def index
    @people = Person.all
  end
  def show
  end
  def new
    @person = Person.new
  end
  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to root_path
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @person.update(person_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  def destroy
    @person.destroy
    redirect_to root_path
  end
  private 
    def set_person
      @person = Person.find(params[:id])
    end
    def person_params
      params.require(:person).permit(:first_name, :last_name, :avatar, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='ui container'>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true, class: 'ui form') do |f| %>
  <div class='field'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true %>
  </div>
  <div class='field'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true %>
  </div>
  <div class='field'>
    <%= f.label :avatar %>
    <%= f.text_field :avatar, required: true %>
  </div>
  <div class='field'>
    <%= f.label :phone %>
    <%= f.text_field :phone, required: true %>
  </div>
  <div class='field'>
    <%= f.label :email %>
    <%= f.text_field :email, required: true %>
  </div>
  <%= f.submit nil, class: "ui secondary button" %>
<% end %>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1 class='ui header blueHeader'>People</h1>
<br />
<%= link_to "New Person", new_person_path %>

<table class="ui celled table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Avatar</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td data-label="First Name"><%= person.first_name %></td>
        <td data-label="Last Name"><%= person.last_name %></td>
        <td data-label="Avatar">
          <img class="ui avatar image" src=<%= person.avatar %>>
        </td>
        <td data-label="Phone"><%= person.phone %></td>
        <td data-label="Email"><%= person.email %></td>
        <td data-label="Actions">
          <%= link_to "Show", person_path(person) %>
          <%= link_to "Edit", edit_person_path(person) %>
          <%= link_to "Delete", person, method: :delete %>
        </td>
      </tr>
      <% %>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1 class='ui header'>New Person</h1>

<%= render "form" %>
<%= link_to "Back", root_path %>

app/views/people/show.html.erb
<h1>People#show</h1>
<p>Find me in app/views/people/show.html.erb</p>